add_newline = true
command_timeout = 1500

[character]
success_symbol = '[â¯](bold green)'

[cmd_duration]
disabled = true

[git_branch]
style = 'bold yellow'

[git_status]
untracked = "U"

[package]
disabled = true

[python]
detect_extensions = [".python-version"]
detect_folders = [".venv", "venv"]
